In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])

print(np.random.choice(a, 2, replace=False))

[3 2]


In [6]:
weights = np.random.randn(5, 3)
print(weights)
print(weights * 0.0001)

[[ 0.41564328  0.36333486  0.35120571]
 [-0.89982128  0.88416108  0.41051421]
 [-0.23601486  1.32586245  0.04027974]
 [ 0.05292986  1.8274266   0.79188422]
 [ 2.4432737   1.62045883 -1.07912125]]
[[ 4.15643278e-05  3.63334863e-05  3.51205708e-05]
 [-8.99821284e-05  8.84161083e-05  4.10514215e-05]
 [-2.36014857e-05  1.32586245e-04  4.02797383e-06]
 [ 5.29298552e-06  1.82742660e-04  7.91884218e-05]
 [ 2.44327370e-04  1.62045883e-04 -1.07912125e-04]]


In [8]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
binary = a % 2 == 0
print(binary)

[[False  True False]
 [ True False  True]
 [False  True False]]


In [7]:
alpha = 1
binary = alpha > 0
print(binary)

True
