# Scipy

In [3]:
import numpy as np
from scipy.spatial.distance import pdist, squareform

In [4]:
# Create the following array where each row is a point in 2D space:
# [[0 1]
#  [1 0]
#  [2 0]]
x = np.array([[0, 1], [1, 0], [2, 0]])
print(x)

[[0 1]
 [1 0]
 [2 0]]


In [5]:
# Compute the Euclidean distance between all rows of x.
# d[i, j] is the Euclidean distance between x[i, :] and x[j, :],
# and d is the following array:
# [[ 0.          1.41421356  2.23606798]
#  [ 1.41421356  0.          1.        ]
#  [ 2.23606798  1.          0.        ]]
d = squareform(pdist(x, 'euclidean'))
print(d)

[[0.         1.41421356 2.23606798]
 [1.41421356 0.         1.        ]
 [2.23606798 1.         0.        ]]


In [6]:
# Calculations of D
# d[0, 0] = x[0, 0] - x[0, 0] = 0
# d[0, 1] = sqrt((x[0, 0] - x[1, 0])^2 + (x[0, 1] - x[1, 1])^2) = sqrt(1^2 + 1^2) = sqrt(2)
# d[0, 2] = sqrt((x[0, 0] - x[2, 0])^2 + (x[0, 1] - x[2, 1])^2) = sqrt(2^2 + 1^2) = sqrt(5)
